# Generated by Django 5.1.4 on 2024-12-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
